name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code
        run: echo "Linting repository"

      - name: Run Unit Tests
        run: echo "Running unit tests"

  deploy-to-ec2:
    name: Continuous Deployment to EC2
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Transfer Files to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Use rsync to copy the files to the EC2 instance
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_PUBLIC_IP:/home/$EC2_USER/project-directory

      - name: Run Remote Commands on EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_PUBLIC_IP << 'EOF'
            # Navigate to project directory
            cd /home/$EC2_USER/project-directory

            # Install dependencies and run any necessary setup
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

            # Start the application (replace with your actual start command)
            nohup python3 app.py > app.log 2>&1 &
          EOF
