name: workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
permissions:
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint code
        run: echo "Linting repository"
      - name: Run unit tests
        run: echo "Running unit tests"

  deploy-to-ec2:
    name: Deploy to EC2
    needs: integration
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Sync repository to EC2
        run: |
          # Create backup of existing code (optional)
          timestamp=$(date +%Y%m%d_%H%M%S)
          if [ -d "/path/to/your/app" ]; then
            cp -r /path/to/your/app "/path/to/your/app_backup_${timestamp}"
          fi
          
          # Sync new code to application directory
          rsync -av --exclude '.git' --exclude '.github' ./ /path/to/your/app/
          
          # Set proper permissions (adjust as needed)
          chmod -R 755 /path/to/your/app
